spring:
  application:
    name: config-server  
  cloud:
    config:
      server:
        git:
          search-paths: config #远程配置文件搜索目录
          basedir: /config/
          uri: https://github.com/554557313/spring-cloud.git #远程仓库地址
          username: 554557313@qq.om
          password: ghw162534
      label: master
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
        health-check-path: /actuator/health  #健康检查端点
        health-check-interval: 10s
server:
  port: 8081